### PR TITLE
Fixed cursor in title in HTML mode (for issue #714).

### LINKED ISSUE #714: Cursor in title field in jumps to end (HTML mode)
As reported by a user:

> If you switch the editor to HTML mode, the cursor in the title field jumps to the end after every edit.

Video: https://cloudup.com/idG1lFDZZd0

### PR DESCRIPTION
**Pull request by diegoreymendez**
Fixes #714.

**Test 1:**
1. Launch the demo app.
2. Switch to HTML mode.
3. Edit the title right moving the caret around, and make sure the caret doesn't jump to the end.

**Test 2:**
1. Using WPiOS branch `editor/714-cursor-jumping-to-end`.
2. Launch WPiOS.
3. Create or edit a post.
4. Switch to HTML mode.
5. Edit the title and make sure the caret's position doesn't move to the end.
6. Make sure whatever changes you make to the title are properly saved.

/cc @SergioEstevao for review.

### CODE REVIEW

File: Classes/WPEditorView.m [hunk 1]
```diff
@@ -217,7 +219,15 @@ - (void)observeValueForKeyPath:(NSString *)keyPath
...
-    }
+	}
+}
+
+- (void)startObservingTitleFieldChanges
+{
+	[[NSNotificationCenter defaultCenter] addObserver:self
+											 selector:@selector(titleTextDidChange)
+												 name:UITextFieldTextDidChangeNotification
+											   object:nil];
```
Comment (bummytime) [inline Classes/WPEditorView.m]: Formatting issue? ^

Comment (diegoreymendez) [inline Classes/WPEditorView.m]: I think the latest versions of Xcode are ignoring the project default for spaces vs tabs.

Comment (diegoreymendez) [inline Classes/WPEditorView.m]: ...and using the user default in all cases, instead.

**Comment by SergioEstevao** [comment]
:shipit:
