### PR TITLE
Fix for HTML mode switching hack

### LINKED ISSUE #777: Stop switching to HTML mode when trait collections change
[This hack](https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/b6daeeddd17869ffce07eeffb267bb6ce7b1da75/Classes/WPEditorViewController.m#L1063) was originally used to fix an issue where the format bar would not resize properly when the editor was rotated or resized. See:

https://cloudup.com/cdTeoqvavQb

Turns out that the switching back and forth from HTML mode is causing all kinds of issues when uploading media. We should fix this ASAP.

### PR DESCRIPTION
**Pull request by bummytime**
Fixes #777 

Updates the hack that was originally used to fix an issue where the format bar would not resize properly when the editor was rotated or resized. Now, instead of switching modes, we blur and refocus the field which updates the input accessory view and forces it to resize properly. Doing this allows media to upload without being interrupted.

Things to test:

* Run the app on an Air2 or iPad Pro. Use multitasking in various ways...make sure the format bar resizes. Upload media while doing this and make sure it is not interrupted.
* Run the app various iPhones....make sure the format bar resizes. Upload media while doing this and make sure it is not interrupted.
* Upload media while rotating the device.

/cc @SergioEstevao

### CODE REVIEW

File: Classes/WPEditorViewController.m [hunk 1]
```diff
@@ -1062,18 +1062,19 @@ - (void)showInsertImageAlternatePicker
...
-        // Important: This is a complete and utter hack that compensates for the input accessory view
-        // not properly changing size classes (resizing) when the rest of the views in the editor VC do.
-        // Toggling the HTML button on the input bar quickly does not affect the view and forces the
-        // input accessory view (the format bar) to update itself. FWIW, setNeedsDisplay and
-        // setNeedsLayout do NOT work.
         if ([self.editorView isInVisualMode]) {
-            [self.editorView showHTMLSource];
-            [self.editorView showVisualEditor];
+            [[self.editorView focusedField] blur];
+            [[self.editorView focusedField] focus];
```
Comment (SergioEstevao) [inline Classes/WPEditorViewController.m]: I noticed that we where loosing the focus and selection on rotation, if we change the code like this it looks it works better: 
```
 WPEditorField *field = [self.editorView focusedField];
            [self.editorView saveSelection];
            [field blur];
            [field focus];
            [self.editorView restoreSelection];
```

Can you test on your iPad Pro to see if we don't mess up anything.

Comment (bummytime) [inline Classes/WPEditorViewController.m]: Good add @SergioEstevao! Works great on the iPad Pro with multitasking and rotation.

**Comment by SergioEstevao** [comment]
One last question, do we really need to do the dance of resign/becomeFirstResponder on the source code view? In there we are using the standard UITextView and no hack for the acessoryInputView so should the rotation work by itself?

**Comment by bummytime** [comment]
@SergioEstevao Unfortunately, yes:

screen shot 2016-03-03 at 11 21 27 am

**Comment by SergioEstevao** [comment]
ok then so :shipit:
