### PR TITLE
Detect media removal on the editor by the user.

### LINKED ISSUE #643: Backspace breaks uploads
Video of the issue [here](https://lookback.io/watch/xLJENJzYQEhaCZted).

*Steps to reproduce:*
- Upload a video in the editor
- Make sure the caret is placed right after the video as it is uploading.
- Press backspace.

*Expected behaviour:* the upload should be cancelled.
*Current behaviour:* Can't close the post, the "Uploading..." message is still shown.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Closes #643 

How to test:

Add images or videos to the editor and then remove it by using backspace. 

Check if the - (void)editorViewController:(WPEditorViewController *)editorViewController mediaRemoved:(NSString *)mediaID

callback method is being called on the WPViewController class on the EditorDemo project.

This will need a follow up PR on the WordPress main project to 

@diegoreymendez and @bummytime can you guys have a look on this?

### CODE REVIEW

File: Assets/ZSSRichTextEditor.js [hunk 1]
```diff
@@ -1991,6 +2028,27 @@ ZSSField.prototype.bindListeners = function() {
     this.wrappedObject.bind('input', function(e) { thisObj.handleInputEvent(e); });
     this.wrappedObject.bind('compositionstart', function(e) { thisObj.handleCompositionStartEvent(e); });
     this.wrappedObject.bind('compositionend', function(e) { thisObj.handleCompositionEndEvent(e); });
+    
+    var target = this.wrappedObject[0];
```
Comment (diegoreymendez) [inline Assets/ZSSRichTextEditor.js]: Just to separate concerns a bit, I'd recommend to place the code to create / initialize the mutation observer in a method of it's own and call it here with a single line instead.  It feels like this method should handle a higher level logic.

File: Assets/ZSSRichTextEditor.js [hunk 2]
```diff
@@ -710,6 +710,23 @@ ZSSEditor.getImageContainerNodeWithIdentifier = function(imageNodeIdentifier) {
...
+    }
+    return (node.id.search("img_container_") == 0) || (node.id.search("video_container_") == 0);
+};
+
+ZSSEditor.extractMediaIdentifier = function(node) {
+    if (node.id.search("img_container_") == 0) {
+        return node.id.replace("img_container_", "");
+    }
+    
+    if (node.id.search("video_container_") == 0) {
```
Comment (diegoreymendez) [inline Assets/ZSSRichTextEditor.js]: Since a single node should only have one identifier, why not place this condition in an else clause?  That way we will avoid evaluating both if "img_container_" is found.

File: Assets/ZSSRichTextEditor.js [hunk 3]
```diff
@@ -888,15 +907,29 @@ ZSSEditor.removeImage = function(imageNodeIdentifier) {
...
         imageContainerNode.remove();
     }
 };
 
 /**
+ *  @brief      Callbacks to native that the media container was deleted by the user
+ *
+ *  @param      mediaNodeIdentifier     The unique media ID
+ */
+ZSSEditor.sendMediaRemovedCallback = function( mediaNodeIdentifier ) {
```
Comment (diegoreymendez) [inline Assets/ZSSRichTextEditor.js]: Remove the extra spacing between parenthesis and parameters.

Do the same for the calls inside this method.

File: Classes/WPEditorViewController.h [hunk 4]
```diff
@@ -100,6 +100,15 @@ WPEditorViewControllerMode;
...
        videoPressInfoRequest:(NSString *)videoID;
 
+/**
+ *	@brief		Received when the editor removed an uploading media.
+ *
+ *	@param		editorView	The editor view.
+ *	@param		mediaID		The id of the media that was removed.
+ */
+- (void)editorViewController:(WPEditorViewController *)editorViewController
+       mediaRemoved:(NSString *)mediaID;
```
Comment (diegoreymendez) [inline Classes/WPEditorViewController.h]: Tab alignment is off.

**Comment by diegoreymendez** [comment]
@SergioEstevao - First review is complete... I tested it and it seems to be working all right.  Please check my comments and let me know when this is ready for another look.

**Comment by diegoreymendez** [comment]
:shipit:
