### PR TITLE
Issue/701 app crashes when changing title after video upload

### LINKED ISSUE #701: App crashes when changing post title after uploading a video
Related to this issue on the main app https://github.com/wordpress-mobile/WordPress-iOS/issues/4098

### PR DESCRIPTION
**Pull request by SergioEstevao**
Closes #701 

Sorts some issues around poster video loading and metadata loading in order to make loading of videos on the editor a lighter operation.

Needs Review: @bummytime

### CODE REVIEW

File: Classes/WPEditorView.m [hunk 1]
```diff
@@ -1559,11 +1559,15 @@ - (void)replaceLocalVideoWithID:(NSString *)uniqueID
...
 {
-    NSString * videoPressSafeID = videoPressID;
+    NSString *videoPressSafeID = videoPressID;
     if (!videoPressSafeID) {
         videoPressSafeID = @"";
     }
-    NSString *trigger = [NSString stringWithFormat:@"ZSSEditor.replaceLocalVideoWithRemoteVideo(\"%@\", \"%@\", \"%@\", \"%@\");", uniqueID, videoURL, posterURL, videoPressSafeID];
+    NSString *posterURLSafe = posterURL;
+    if (!posterURLSafe) {
+        posterURLSafe = @"";
```
Comment (bummytime) [inline Classes/WPEditorView.m]: Was this the root cause of the crasher before (`posterURL` was `nil`)?

Comment (SergioEstevao) [inline Classes/WPEditorView.m]: I thought so initially, but this was just the tip of the iceberg. Have a look on this PR https://github.com/wordpress-mobile/WordPress-iOS/pull/4116 for further details.

**Comment by bummytime** [comment]
Ok @SergioEstevao I will look at the other PR. For this one, it's a :shipit:
